version: '3'

services:
  app:
    container_name: 'notion'
    build: .
    volumes:
      - ~/.ssh:/home/node/.ssh
      - .:/home/node/notion
      - /home/node/notion/node_modules
    ports:
      - '3005:3005'
    stdin_open: true
    tty: true
